import "./globals.css";
import type { Metadata } from "next";
import Head from "next/head";
import { Suspense } from "react";

import { Navbar, Background } from "@/components/exports";
import Loading from "./loading";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Operax-The Game Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <Head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </Head>

      <body>
        <Providers>
          {/**The Navbar is here so that it can be access through out the application */}
          <Navbar />
          <Background>
            <div className="isolate px-6 pt-14 lg:px-8 ">
              {/**The Top and the Bottom Divs are for background */}
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </div>
          </Background>
        </Providers>
      </body>
    </html>
  );
}
